const DEFAULT_ACTIVE_BUTTON_OPACITY = .7;
const DEFAULT_BUTTON_TEXT_FONT_SIZE = 18;
const PRIMARY_COLOR = 'rgb(24, 128, 251)';
const PRIMARY_TEXT_COLOR = 'rgb(255,255,255)';
const DEFAULT_BUTTON_STYLE = {
  padding: 16,
  borderRadius: 8,
  alignItems: 'center',
  justifyContent: 'center',
};

export {
  DEFAULT_ACTIVE_BUTTON_OPACITY,
  DEFAULT_BUTTON_TEXT_FONT_SIZE,
  PRIMARY_COLOR,
  PRIMARY_TEXT_COLOR,
  DEFAULT_BUTTON_STYLE,
};